All good
--------------------------------------------------
Traceback (most recent call last):

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 119, in <module>
    with open(f'.\\{config_path}\\keys.txt', 'r') as file: keys = file.read()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: '.\\Depandances\\Config\\keys.txt'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 16, in create_dir_if_unexisting
    try: v_dir.index(name)
         ^^^^^^^^^^^^^^^^^

ValueError: 'Depandances\\Config' is not in list


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 18, in create_dir_if_unexisting
    try: os.mkdir(f"{path}\\{name}")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: './\\Depandances\\Config'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\TR_main.py", line 15, in <module>
    from TR_setup import setup

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\TR_setup.py", line 3, in <module>
    from TR_imageaison import img_cart1, img_cart2, img_chrg

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\TR_imageaison.py", line 3, in <module>
    from Depandances.Outils.paths__names__etc import *

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 121, in <module>
    create_dir_if_unexisting(config_path)

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 19, in create_dir_if_unexisting
    except: print(v_dir); raise Exception
                          ^^^^^^^^^^^^^^^

Exception

--------------------------------------------------
Traceback (most recent call last):

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 119, in <module>
    with open(f'.\\{config_path}\\keys.txt', 'r') as file: keys = file.read()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: '.\\Depandances\\Config\\keys.txt'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 16, in create_dir_if_unexisting
    try: v_dir.index(name)
         ^^^^^^^^^^^^^^^^^

ValueError: 'Depandances\\Config' is not in list


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 18, in create_dir_if_unexisting
    try: os.mkdir(f"{path}\\{name}")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: './\\Depandances\\Config'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\TR_main.py", line 15, in <module>
    from TR_setup import setup

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\TR_setup.py", line 3, in <module>
    from TR_imageaison import img_cart1, img_cart2, img_chrg

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\TR_imageaison.py", line 3, in <module>
    from Depandances.Outils.paths__names__etc import *

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 121, in <module>
    create_dir_if_unexisting(config_path)

  File "c:\Users\Tim\Documents\GitHub\TR_TT-AC\Depandances\Outils\paths__names__etc.py", line 19, in create_dir_if_unexisting
    except: print(', '.join(n for n in v_dir), name); raise Exception
                                                      ^^^^^^^^^^^^^^^

Exception
